### ISSUE TITLE
Do you need a separate implementation for this project?

### ISSUE THREAD

**Issue by mohittahiliani** [bijaydev/Implementation-of-Explicit-congestion-notification-ECN-in-TCP-over-wireless-network-in-ns-3#1]
I do not think there is a need for a separately implementing a header and cc for this project.

IMO, an existing TCP like NewReno can be extended to support this feature.

For example, set up a boolean variable called "m_isEcnResponse" and whenever this is true - NewReno should respond the way paper describes.

I'm not very sure, but I feel strongly that you do not need a separate implementation.

**Comment by suraj-ravi93** [comment]
Sir,
The idea was suggested to us by Ankit when we discussed about the ECN project with him and Shravya. They told us that it is not a good practice to modify the existing NewReno.We will make the necessary changes as you told.

**Comment by bijaydev** [comment]
Sir,
   We have made the necessary changes.
